service:
  name: sls-notes-api

custom:
  serverless-offline:
    prefix: notes

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  apiName: SLS Notes Api
  description: Notes Microservice for a Serverless Demo
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}'

functions:
  get-notes:
    handler: get-notes.handler
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers: ${file(../../utils/customHeaders.yml)}

  create-note:
    handler: create-note.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
            headers: ${file(../../utils/customHeaders.yml)}

  update-note:
    handler: update-note.handler
    events:
      - http:
          path: /
          method: put
          cors:
            origin: '*'
            headers: ${file(../../utils/customHeaders.yml)}

  get-note:
    handler: get-note.handler
    events:
      - http:
          path: /notes/{noteId}
          method: get
          cors:
            origin: '*'
            headers: ${file(../../utils/customHeaders.yml)}

  delete-note:
    handler: get-note.handler
    events:
      - http:
          path: /{timestamp}
          method: post
          cors:
            origin: '*'
            headers: ${file(../../utils/customHeaders.yml)}
