service:
  name: sls-notes-api

custom:
  typeScript:
    tsconfigFilePath: ../../../tsconfig.json
  serverless-offline:
    prefix: notes

plugins:
  - '@kingdarboja/serverless-plugin-typescript'
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  apiName: SLS Notes Api
  description: Notes Microservice for a Serverless Demo
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}

resources:
  Resources: ${file(../../utils/notesTable.yml)}

functions:
  create-note:
    handler: create-note.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
  # get-admins:
  #   handler: get-notes.handler
  #   events:
  #     - http:
  #         path: /
  #         method: get
  #         cors:
  #           origin: '*'
  # get-admin:
  #   handler: get-note.handler
  #   events:
  #     - http:
  #         path: /{noteId}
  #         method: post
  #         cors:
  #           origin: '*'
