service:
  name: sls-notes-api-users

custom:
  typeScript:
    tsconfigFilePath: ../../../tsconfig.json
  serverless-offline:
    prefix: users

plugins:
  - '@kingdarboja/serverless-plugin-typescript'
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  apiName: SLS Notes Api
  description: Users Microservice for a Serverless Demo
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}

functions:
  login:
    handler: login.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
