service:
  name: sls-notes-api

custom:
  customDomain:
    domainName: '${env:API_NAME}.maigoapp.com'
    basePath: 'users'
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: trues
    packager: 'yarn'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-east-1
  apiName: Sls Notes Api
  description: Users Microservice for a Serverless Demo
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT}

functions:
  login:
    handler: login.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
